baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Hugo xx Project"
theme = "basic"

[params]
  author = "Brian Hogan"
  description = "My portfolio site"
  gh_url = "https://api.github.com/users"
  gh_user = "wu0655"
